<%@ page language="C#" autoeventwireup="true" inherits="Report_Payroll_NetPaymentListByPaymentMethod_List, HROneWeb.deploy" masterpagefile="~/MainMasterPage.master" maintainscrollpositiononpostback="true" viewStateEncryptionMode="Always" %>

<%@ Register Src="~/controls/RecordListFooter.ascx" TagName="RecordListFooter" TagPrefix="tb" %>
<%@ Register Src="~/controls/ReportExportControl.ascx" TagName="ReportExportControl" TagPrefix="uc3" %>
<%@ Register Src="~/controls/WebDatePicker.ascx" TagName="WebDatePicker" TagPrefix="uc1" %>
<%-- Start 0000185, KuangWei, 2015-04-21 --%>
<%@ Register Src="~/controls/EmployeeSearchControl.ascx" TagName="EmployeeSearchControl" TagPrefix="uc2" %>
<%-- End 0000185, KuangWei, 2015-04-21 --%>
<asp:Content ID="Content1" ContentPlaceHolderID="mainContentPlaceHolder" runat="server">
<%-- Start 0000004, Miranda, 2014-06-19 --%>
<input type="hidden" id="hiddenFieldDefaultMonthPeriod" runat="server" value="1" />
<%-- End 0000004, Miranda, 2014-06-19 --%>
	<table border="0" cellpadding="0" cellspacing="0" width="100%" class="pm_page_title">
         <tr>
             <td>
                    <asp:Label ID="lblReportHeader" runat="server" Text="Net Payment Report by Payment Method" />
             </td>
         </tr>
    </table>
	<table border="0" cellpadding="0" cellspacing="0" width="100%" class="pm_section_title">
        <tr>
            <td>
                <asp:Label runat="server" Text="Payroll Group Information" />
            </td>
        </tr>
    </table>
    <table width="100%" class="pm_section">
        <tr>
            <td class="pm_field_header">
                <asp:Label runat="server" Text="Payroll Cycle" />:
            </td>
            <td class="pm_search">
                <%-- Start 0000004, Miranda, 2014-06-19 --%>
                <uc1:WebDatePicker id="PayPeriodFr" runat="server" OnChanged="PayPeriod_Changed" AutoPostBack="true" />
                -
                <uc1:WebDatePicker id="PayPeriodTo" runat="server" OnChanged="PayPeriod_Changed" AutoPostBack="true" />
                <%-- End 0000004, Miranda, 2014-06-19 --%>
                <asp:Button ID="Search" runat="server" Text="Search" CssClass="button" OnClick="Search_Click" />
            </td>
        </tr>
        <tr>
            <td class="pm_field_header">
                <asp:Label ID="Label1" runat="server" Text="Payment Method" />:
            </td>
            <td class="pm_search">
                <asp:CheckBox ID="chkAutoPay" runat="server" Text="Autopay" Checked="True" />
                <asp:CheckBox ID="chkCheque" runat="server" Text="Cheque" Checked="True" />
                <asp:CheckBox ID="chkCash" runat="server" Text="Cash" Checked="True" />
                <asp:CheckBox ID="chkOthers" runat="server" Text="Others" Checked="True" />
            </td>
        </tr>
    </table>
    
        
            
    
    <asp:Panel ID="panelPayPeriod" runat="server">
        <table border="0" width="100%" class="pm_list_section" cellspacing="0" cellpadding="1">
            <col width="26px" />
            <col width="150px" />
            <col width="150px" />
            <col width="120px" />
            <col width="120px" />
            <col width="120px" />
            <col width="100px" />
            <tr>
                <td class="pm_list_header" align="center">
                    <input type="checkbox" onclick="checkAll('<%=payBatchRepeater.ClientID %>','ItemSelect',this.checked);" />
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayGroupDesc" OnClick="payBatchChangeOrder_Click" Text="Payroll Group"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayPeriodFr" OnClick="payBatchChangeOrder_Click" Text="Period"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayBatchConfirmDate" OnClick="payBatchChangeOrder_Click" Text="Confirm Date"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayBatchFileGenDate" OnClick="payBatchChangeOrder_Click" Text="Last Generation Date"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayBatchValueDate" OnClick="payBatchChangeOrder_Click" Text="Previous Value Date"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayBatchFileGenBy" OnClick="payBatchChangeOrder_Click" Text="Generated By"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_PayBatchRemark" OnClick="payBatchChangeOrder_Click" Text="Remark"/>
                </td>
            </tr>
            <asp:Repeater ID="payBatchRepeater" runat="server" OnItemDataBound="payBatchRepeater_ItemDataBound">
                <ItemTemplate>
                    <tr>
                        <td class="pm_list" align="center">
                            <asp:CheckBox ID="ItemSelect" runat="server" Checked="True" />
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getValue(Container.DataItem, "PayGroupDesc")%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getFValue(Container.DataItem, "PayPeriodFr","yyyy-MM-dd" )%>
                            <asp:Label runat="server" Text="To" />
                            <%#payBatchSBinding.getFValue(Container.DataItem, "PayPeriodTo","yyyy-MM-dd" )%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getFValue(Container.DataItem, "PayBatchConfirmDate","yyyy-MM-dd HH:mm:ss")%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getFValue(Container.DataItem, "PayBatchFileGenDate", "yyyy-MM-dd HH:mm:ss")%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getFValue(Container.DataItem, "PayBatchValueDate", "yyyy-MM-dd")%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getValue(Container.DataItem, "PayBatchFileGenBy")%>
                        </td>
                        <td class="pm_list">
                            <%#payBatchSBinding.getValue(Container.DataItem, "PayBatchRemark")%>
                        </td>
                    </tr>
                </ItemTemplate>
            </asp:Repeater>
        </table>
        <table width="100%" cellspacing="0" cellpadding="0" class="pm_list_pagenav">
            <tr>
                <td align="right">
                    <tb:RecordListFooter id="PayBatchListFooter" runat="server"
                        ShowAllRecords="true" 
                      />
                </td>
            </tr>
        </table>
		<br/>
		<asp:Panel ID="panelEmployeeList" runat="server" >
        <table border="0" cellpadding="0" cellspacing="0" width="100%" class="pm_section_title">
            <tr>
                <td>
                    <asp:Label runat="server" Text="Employee List" />
                </td>
            </tr>
        </table>
       <%-- Start 0000185, KuangWei, 2015-04-21 --%>
        <asp:UpdatePanel ID="SearchUpdatePanel" runat="server" UpdateMode="Conditional" >
            <ContentTemplate >
                <uc2:EmployeeSearchControl id="EmployeeSearchControl1" runat="server" />
            </ContentTemplate >
        </asp:UpdatePanel>
        
        <table width="100%" cellpadding="0" cellspacing="0" class="pm_button_section">
            <tr>
                <td>
                    <asp:Button ID="EmployeeSearch" runat="server" Text="Search" CssClass="button" OnClick="EmployeeSearch_Click" />
                    <asp:Button ID="Reset" runat="server" Text="Reset" CssClass="button" OnClick="Reset_Click" />
                </td>
            </tr>
        </table>    
        <%-- End 0000185, KuangWei, 2015-04-21 --%>        
        <table class="pm_section" width="100%">
            <tr>
                <td>
                    <uc3:ReportExportControl id="ReportExportControl2" runat="server"  OnClick="btnGenerate_Click" ButtonCssClass="button"/>
                </td>
            </tr>
        </table>        
        <table border="0" width="100%" class="pm_list_section" cellspacing="0" cellpadding="1">
            <col width="26px" />
            <col width="150px" />
            <colgroup width="350px" >
                <col width="150px" />
                <col />
            </colgroup> 
            <col width="150px" />
            <col width="100px" />
            <tr>
                <td class="pm_list_header" align="center">
                    <asp:Panel ID="EmployeeSelectAllPanel" runat="server">
                    <input type="checkbox" onclick="checkAll('<%=empRepeater.ClientID %>','ItemSelect',this.checked);" />
                </asp:Panel>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_EmpNo" OnClick="empChangeOrder_Click" Text="Emp No"/>
                </td>
                <td align="left" class="pm_list_header" colspan="2">
                    <asp:LinkButton runat="server" ID="_EmpEngFullName" OnClick="empChangeOrder_Click" Text="Name"/>
                </td>
                <td align="left" class="pm_list_header">
                    <asp:LinkButton runat="server" ID="_EmpAlias" OnClick="empChangeOrder_Click" Text="Alias"/>
                </td>
            </tr>
            <asp:Repeater ID="empRepeater" runat="server" OnItemDataBound="empRepeater_ItemDataBound">
                <ItemTemplate>
                    <tr>
                        <td class="pm_list" align="center">
                            <asp:CheckBox ID="ItemSelect" runat="server" Checked="True" />
                        </td>
                        <td class="pm_list">
                            <a href="<%#HROne.Common.WebUtility.URLwithEncryptQueryString(Session, "Emp_View.aspx?EmpID=" + empSBinding.getValue(Container.DataItem,"EmpID"))%>">
                                <%#empSBinding.getValue(Container.DataItem, "EmpNo")%>
                            </a>
                        </td>
                        <td class="pm_list">
                            <%#empSBinding.getValue(Container.DataItem, "EmpEngSurname")%>
                        </td>
                        <td class="pm_list">
                            <%#empSBinding.getValue(Container.DataItem, "EmpEngOtherName")%>
                        </td>
                        <td class="pm_list">
                            <%#empSBinding.getValue(Container.DataItem, "EmpAlias")%>
                        </td>
                    </tr>
                </ItemTemplate>
            </asp:Repeater>
        </table>
        <table width="100%" cellspacing="0" cellpadding="0" class="pm_list_pagenav">
            <tr>
                <td>
                            <uc3:ReportExportControl id="ReportExportControl1" runat="server"  OnClick="btnGenerate_Click" ButtonCssClass="button"/>
                </td>
                <td align="right">
                    <tb:RecordListFooter id="EmpListFooter" runat="server"
                        ShowAllRecords="true" 
                      />
                </td>
            </tr>
        </table>
        </asp:Panel> 
    </asp:Panel>
</asp:Content> 