SET IDENTITY_INSERT LeaveCode ON

INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(1,'AL','Annual Leave',1,1.0000,29,28,1,4,NULL,NULL,0,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(2,'FPSL','Full Paid Sick Leave',2,1.0000,31,30,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(3,'SLL','Sick Leave In Law (4/5)',2,0.8000,32,30,1,4,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(4,'NPL','No Pay Leave',5,0.0000,13,34,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(5,'FPML','Full Pay Maternity Leave',4,1.0000,16,33,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(6,'CML','Compensation Leave',6,1.0000,13,11,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(7,'MLL','Maternity Leave In Law',4,0.8000,15,33,1,4,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(8,'NPML','No Pay Maternity Leave',4,0.0000,13,21,1,4,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(9,'NPSL','No Pay Sick Leave',5,0.0000,13,22,1,4,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(10,'ML','Marriage Leave',6,1.0000,13,11,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(11,'TL','Training Leave',6,1.0000,13,11,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)
INSERT INTO [LeaveCode] ([LeaveCodeID],[LeaveCode],[LeaveCodeDesc],[LeaveTypeID],[LeaveCodePayRatio],[LeaveCodeLeaveAllowPaymentCodeID],[LeaveCodeLeaveDeductPaymentCodeID],[LeaveCodeLeaveDeductFormula],[LeaveCodeLeaveAllowFormula],[LeaveCodePayAdvance],[PaymentCodeID],[LeaveCodeHideInESS],[LeaveCodeIsSkipPayrollProcess],[LeaveCodeIsPayrollProcessNextMonth],[LeaveCodeUseAllowancePaymentCodeIfSameAmount],[LeaveCodeIsCNDProrata],[LeaveCodeIsShowMedicalCertOption])VALUES(12,'EL','Examination Leave',6,1.0000,13,11,1,1,NULL,NULL,0,NULL,NULL,NULL,NULL,1)


SET IDENTITY_INSERT LeaveCode OFF