SET IDENTITY_INSERT LeaveType ON

INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(1,'ANNUAL','Annual Leave',2,1,1,0,0,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(2,'SLCAT1','Sick Leave Category I',1,1,0,0,1,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(3,'SLCAT2','Sick Leave Category II',1,1,0,0,1,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(4,'MAL','Maternity Leave',2,1,0,1,1,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(5,'NPL','No Pay Leave',2,1,1,0,0,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(6,'OL','Other Leave',2,0,1,0,0,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(7,'INJURY','Injury Leave',2,1,0,0,1,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(8,'COMPENSATION','Compensation Leave',2,1,NULL,NULL,NULL,NULL,1,1,1,1,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(9,'REST','Rest Day',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(10,'STATUTORYHOLIDAY','Statutory Holiday',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(11,'BIRTHDAY','Birthday Leave',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0)
INSERT INTO [LeaveType] ([LeaveTypeID],[LeaveType],[LeaveTypeDesc],[LeaveDecimalPlace],[LeaveSystemUse],[LeaveTypeIsUseWorkHourPattern],[LeaveTypeIsSkipStatutoryHolidayChecking],[LeaveTypeIsSkipPublicHolidayChecking],[LeaveTypeIsESSHideLeaveBalance],[LeaveTypeIsESSRestrictNegativeBalanceAsOfToday],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateFrom],[LeaveTypeIsESSRestrictNegativeBalanceAsOfApplicationDateTo],[LeaveTypeIsESSRestrictNegativeBalanceAsOfEndOfLeaveYear],[LeaveTypeIsDisabled])VALUES(12,'PUBLICHOLIDAY','Public Holiday',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0)

SET IDENTITY_INSERT LeaveType OFF