SET IDENTITY_INSERT MPFScheme ON

INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(1,'MT00431','AIA MPF - Simple Value Choice','AIA')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(2,'MT00180','AXA MPF - SMART PLAN','AXA')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(3,'MT00016','Bank Consortium MPF Plan','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(4,'IS00017','Bank Consortium Industry Plan','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(5,'MT00393','BCOM Joyful Retirement MPF Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(6,'MT00407','BCOM Prosperous Retirement MPF Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(7,'MT00202','BEA (MPF) Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(8,'IS00025','BEA (MPF) Industry Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(9,'MT00075','INVESCO Strategic MPF Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(10,'MT00121','Taifook MPF Retirement Fund','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(11,'MT00288','Fidelity Retirement Master Trust','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(12,'MT00296','Manager Elite Master Trust','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(13,'MT00334','Dao Heng MPF Master Trust Plan','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(14,'MT00369','New-Alliance Mandatory Provident Fund Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(15,'MT00490','Dresdner RCM MPF Plan','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(16,'MT00091','BOC-Prudential Easy-Choice Mandatory Provident Fund Scheme','BOCI')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(17,'MT00105','BOCI-Prudential Flexible Mandatory Provident Fund Scheme','BOCI')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(18,'MT00415','Standard Chartered MPF Plan - Advanced','RBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(19,'MT00423','Standard Chartered MPF Plan - Basic','RBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(20,'MT00342','MLC MPF Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(21,'MT00083','China Life MPF Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(22,'MT00067','Sun Life Rainbow MPF Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(23,'MT00385','Chamber CMG Choice (CCC)','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(24,'MT00113','Dresdner RCM MPF Master Trust','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(25,'MT00210','Schroder MPF Master Trust','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(26,'MT00245','HSBC Mandatory Provident Fund - SuperTrust Plus','HSBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(27,'MT00253','Hang Seng Mandatory Provident Fund - SuperTrust Plus','HangSeng')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(28,'MT00261','HSBC Mandatory Provident Fund - SuperTrust','HSBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(29,'MT0027A','Hang Seng Mandatory Provident Fund - SuperTrust','HangSeng')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(30,'MT00377','Manu-Lifestyle (MPF) Scheme','Manulife')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(31,'MT00482','Manulife Global Select (MPF) Scheme','Manulife')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(32,'MT00350','Mass Mandatory Provident Fund Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(33,'MT00229','PCI Master Trust MPF Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(34,'MT00024','Principal MPF Scheme Series 100','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(35,'MT00032','Principal MPF Scheme Series 200','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(36,'MT00040','Principal MPF Scheme Series 600','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(37,'MT00059','Principal MPF Scheme Series 800','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(38,'MT0044A','Eagle Star MPF Scheme - Security Planner','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(39,'MT00458','Eagle Star MPF Scheme - Advance Planner','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(40,'MT00466','Zurich-Chinese Bank MPF Scheme - Premier','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(41,'MT00474','Zurich-Chinese Bank MPF Scheme - PremierDELUXE','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(42,'MT00199','DBS - Kwong On Bank MPF Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(43,'MT00237','RBC MPF Master Trust','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(44,'MT0013A','Tai Ping Retire-Well MPF Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(45,'MT00148','Tai Ping Retire-Easy MPF Master Trust Scheme','Others')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(46,'MT00156','AIA MPF - Basic Value Choice','AIA')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(47,'MT00172','AIA MPF - Prime Value Choice','AIA')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(48,'MT00555','HSBC Mandatory Provident Fund - ValueChoice','HSBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(49,'MT00512','HSBC Mandatory Provident Fund - SimpleChoice','HSBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(50,'MT00520','Hang Seng Mandatory Provident Fund - SimpleChoice','HangSeng')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(51,'MT00563','Hang Seng Mandatory Provident Fund - ValueChoice','HangSeng')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(52,'ES00020','SHKP MPF Employer Sponsored Scheme','RBC')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(53,'MT00504','AXA MPF - Simple Plan','AXA')
INSERT INTO [MPFScheme] ([MPFSchemeID],[MPFSchemeCode],[MPFSchemeDesc],[MPFSchemeTrusteeCode])VALUES(54,'MT00547','My Choice Mandatory Provident Fund Scheme','BOCI')

SET IDENTITY_INSERT MPFScheme OFF