SET IDENTITY_INSERT SystemFunction On

INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(1,'SYS000','System Parameter Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(2,'SYS001','Company Setting','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(3,'SYS002','Business Hierarchy Level Setting','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(4,'SYS003','Business Hierarchy Setting','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(5,'SYS004','Payment Code Setting','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(6,'SYS005','Miscellaneous Code Setting','System',-1)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(7,'SYS006','Holiday Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(8,'SEC001','User Maintenance Setting','Security',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(9,'SEC002','User Group Setting','Security',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(10,'PER001','Employee Personal Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(11,'PER002','Employee Bank Account Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(12,'PER003','Employee Spouse/Dependant Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(13,'PER004','Employee Qualification/Skills','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(14,'PER005','Employee Accommodation Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(15,'PER006','Employee Contracts Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(16,'PER007','Employee Position Terms Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(17,'PER008','Employee Pension Terms Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(18,'PER009','Employee Leave Application History Enquiry','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(19,'PER010','Employee Leave Balance Enquiry','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(20,'PER011','Employee Termination','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(21,'LEV001','Leave Type Setting','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(22,'LEV002','Leave Code Setting','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(23,'LEV003','Leave Plan Setting','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(24,'PAY001','Payroll Group Setting','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(25,'PAY002','Payroll Formula Setup','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(26,'PAY003','Claims and Deductions','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(27,'PAY004','Payroll Trial Run','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(28,'PAY005','Payroll Trial Run Adjustment','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(29,'PAY006','Rollback Payroll Trial Run','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(30,'PAY007','Payroll Confirmation','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(31,'PAY008','Payroll Process End','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(32,'PAY009','Payroll History Adjustment','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(33,'PAY010','Bank File Generation','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(34,'PAY011','Generate MPF File','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(35,'MPF001','MPF Plan Setting','MPF',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(36,'MPF002','MPF Parameter Setting **','MPF',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(37,'MPF003','AVC Plan Setting','MPF',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(38,'MPF004','P-fund Plan Setup','MPF',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(39,'TAX001','Taxation Company','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(40,'TAX002','Taxation Category Mapping','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(41,'TAX003','Taxation Generation','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(42,'TAX004','Taxation Adjustment','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(43,'TAX005','Taxation Diskette Generation','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(44,'RPT001','Employee','Report',1)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(45,'RPT002','Payroll & MPF','Report',1)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(46,'RPT003','Taxation','Report',1)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(47,'SYS007','Year End Bonus Plan Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(48,'PER012','Employee Cost Center','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(49,'CST001','Cost Allocation Trial Run','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(50,'CST002','Cost Allocation Trial Run Adjustment','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(51,'CST003','Cost Allocation Confirmation','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(52,'CST004','Cost Allocation Detail Export','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(53,'CST005','Cost Allocation Summary Export','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(54,'ATT001','Roster Code Setup','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(55,'ATT002','Attendance Formula Setup','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(56,'ATT003','Attendance Plan Setup','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(57,'ATT004','Export Roster Table','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(58,'ATT005','Import Roster Table','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(59,'ATT006','Import Time Card Record','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(60,'ATT007','Generate Attendance Record','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(61,'ATT008','Attendance Record Adjustment','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(62,'ATT009','Export Attendance Records','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(63,'ATT010','Import Attendance Records','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(64,'ATT011','Generate Attendance Payment','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(65,'SYS999','Audit Trail','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(66,'SEC003','Authorization Group Setup','Security',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(67,'SEC004','Assign Authorizer','Security',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(68,'PER999','Import Employee Information','Personnel',1)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(69,'PER013','Employee Work Permit/License Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(70,'PER014','Employee Document List','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(71,'PAY900','Rollback Payroll Process','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(72,'PER007-1','Employee Recurring Payment Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(73,'PER900','Export Employee Information','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(74,'ATT012','Roster Client Setup','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(75,'MPF005','MPF Termination Code Setup','MPF',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(76,'PER015','Employee Emergency Contact','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(77,'PER016','Employee Working Experience','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(78,'TRA001','Training Course Setup','Training',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(79,'TRA002','Training Seminar Setup','Training',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(80,'TRA003','Training Seminar Enroll','Training',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(81,'TRA004','Training Report','Training',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(82,'LEV004','Annual Leave Prorata Rounding Rule Setup','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(83,'PER017','Employee Work Injury Record','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(84,'SYS009','Work Hour Pattern Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(85,'PAY012','Stop Payment','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(86,'RPT101','Employee List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(87,'RPT102','Employee Contact Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(88,'RPT103','Employee Salary List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(89,'RPT104','Employee Year of Service List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(90,'RPT105','Employee Bank Account List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(91,'RPT106','Employee Details Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(92,'RPT107','Employee Head Count Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(93,'RPT108','Employee Gender Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(94,'RPT109','Employee Residency Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(95,'RPT110','Employee Birthday List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(96,'RPT111','Employee Termination List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(97,'RPT131','Employee Leave Application List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(98,'RPT132','Leave Summary Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(99,'RPT133','Leave Balance List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(100,'RPT151','ESS Pending Request Report','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(101,'RPT201','Payroll Detail Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(102,'RPT202','Payroll Summary Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(103,'RPT203','Employee Daily Average Wages Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(104,'RPT204','Employee Overall Payment Summary','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(105,'RPT205','Pay Slip Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(106,'RPT206','Payroll Discrepancy List','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(107,'RPT207','Net Payment Report by Payment Method','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(108,'RPT208','Payment Summary List','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(109,'RPT209','Payment Allocation Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(110,'RPT251','MPF Details List','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(111,'RPT252','MPF Remittance Statement','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(112,'RPT253','P-Fund Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(113,'RPT300','Taxation Report','Taxation Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(114,'PAY013','Employee Working Summary','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(115,'PAY014','Statutory Minimum Wage Setup','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(116,'RPT210','Statutory Minimum Wage Summary Report','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(117,'ATT013','Roster Table Overview','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(118,'ATT014','Roster Table Group Setup','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(119,'PER018','Employee Compensation Leave Entitlement','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(120,'ATT015','Generate Compensation Leave Entitlement','Attendance',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(121,'RPT211','Final Payment Statement','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(122,'RPT212','Long Service Payment / Severance Payment Estimation List','Payroll & MPF Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(123,'LEV005','Import Leave Balance Adjustment','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(124,'RPT112','New Join Employee List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(125,'RPT113','Employee Probation List','Personnel Reports',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(126,'SYS010','Employment Type Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(127,'SYS011','Cessation Reason Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(128,'SYS012','Position Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(129,'SYS013','Qualification Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(130,'SYS014','Skill Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(131,'SYS015','Skill Level Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(132,'SYS016','Rank Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(133,'SYS017','Staff Type Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(134,'SYS018','Permit Type Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(135,'SYS019','Document Type Code Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(136,'CST000','Cost Center Code Setup','Cost Center',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(137,'ECH000','e-channel Notification','e-channel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(138,'ECH001','Submit Autopay File','e-channel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(139,'ECH002','Submit MPF Contribution File','e-channel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(140,'PAY015','Release Pay Slip to ESS','Payroll',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(141,'SYS001-1','Company Bank Account Setup','System',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(142,'SEC005','ESS Authorization Workflow Setup','Security',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(143,'ECH003','e-channel Signature Setup','e-channel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(144,'TAX006','Release Tax Report to ESS','Taxation',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(145,'PER019','Employee Roster Table Group','Personnel',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(146,'LEV006','Import Compensaion Leave Entitlement','Leave',0)
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(147,'SYS020','PayScale Master', 'System',0);
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(148,'SYS021','PayScale Points Master', 'System',0);
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(149,'PAY016','Payscale - Salary Increment Batch','Payroll',0);
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(150,'PAY017','Payscale - Backpay Template Export','Payroll',0);
INSERT INTO SystemFunction (FunctionID,FunctionCode,Description,FunctionCategory,FunctionIsHidden)VALUES(151,'PAY018','F&V Monthly Achievement','Payroll',0);

SET IDENTITY_INSERT SystemFunction Off