    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>HROne</title>
    <link href="css.css" rel="stylesheet" type="text/css" />
    <script language="javascript" src="calendar/popcalendar.js"></script>
		<script language="javascript" src="date.js"></script>
		<script language="javascript" src="common.js"></script>
    <script language="javascript" src="loadingmessage.js"></script>
	