SET IDENTITY_INSERT TaxPayment ON

INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(1,'B','a','Salary/Wages','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(2,'B','b','Leave Pay','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(3,'B','c','Director''s Fee','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(4,'B','d','Commission/Fees','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(5,'B','e','Bonus','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(6,'B','f','Back Pay, Payment in Lieu of Notice, Terminal Awards or Gratuities','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(7,'B','g','Certain Payments from Retirement Schemes','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(8,'B','h','Salaries Tax Paid by Employer','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(9,'B','i','Education Benefits','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(10,'B','j','Gain realized under share option scheme','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(11,'B','k1','Any Other Rewards, Allowances or Perquisites. Nature:','Allowance','Y')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(12,'B','k2','Any Other Rewards, Allowances or Perquisites. Nature:','Reward','Y')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(13,'B','k3','Any Other Rewards, Allowances or Perquisites. Nature:','NULL','Y')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(14,'B','l','Pensions','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(15,'F','a','Salary/Wages','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(16,'F','b','Leave Pay','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(17,'F','c','Commission/Fees','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(18,'F','d','Payment in Lieu of Notice, Back Pay, Terminal Awards, or Gratuities','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(19,'F','e','Certain Payments from Retirement Schemes','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(20,'F','f','Salaries Tax Paid by Employer','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(21,'F','g','Gain realized under share option scheme','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(22,'F','h','Other Rewards, Allowances or Perquisites, e.g. Bonus, Education Benefits, Shares','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(23,'F','i','Payments that have not been declared above but which will be made AFTER the employee has left employment are:','','Y')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(24,'G','a','Salary/Wages','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(25,'G','b','Leave Pay','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(26,'G','c','Commission/Fees','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(27,'G','d','Payment in Lieu of Notice, Back Pay, Terminal Awards, or Gratuities','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(28,'G','e','Certain Payments from Retirement Schemes','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(29,'G','f','Salaries Tax Paid by Employer','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(30,'G','g','Gain realized under share option scheme','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(31,'G','h','Other Rewards, Allowances or Perquisites, e.g. Bonus, Education Benefits, Shares','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(32,'G','i','Payments that have not been declared above but which will be made AFTER the employee has left employment are:','','Y')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(33,'E','a','Monthly rate of fixed remuneration:','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(34,'E','b','Monthly rate of allowances ( e.g. cost of living) :','','N')
INSERT INTO [TaxPayment] ([TaxPayID],[TaxFormType],[TaxPayCode],[TaxPayDesc],[TaxPayNature],[TaxPayIsShowNature])VALUES(35,'E','c','Fluctuating emoluments ( e.g. commission, bonus, gratuity) :','','N')

SET IDENTITY_INSERT TaxPayment OFF